### ISSUE TITLE
TX/RX Pins on Exp 3 - QUESTION

### ISSUE THREAD

**Issue by axjurado** [Aus3D/RUMBA-Plus#11]
Been trying to connect the Wifi Backpack from Panucatt to the board. I can connect but seems like I cannot make it communicate with he rumba+. 

The documentation says pin 11 and 12 should be tx rx. However, read here in other question that is pin 13 and 14. Not sure which one should use.

Also, not sure what changes is marlin are needed to make this work. 

Appreciate your help. Thanks

**Comment by chrissbarr** [comment]
Hi @axjurado,

UART3 is on pins PJ0 (RX) and PJ1 (TX). These are pin 11 and 12, from the below part of the schematic:

![image](https://user-images.githubusercontent.com/5538631/82975690-5b544800-a01c-11ea-8d24-612ff05a9dbb.png)

Here's a top-down view of the EXP3 connector pinout:

![image](https://user-images.githubusercontent.com/5538631/82975729-73c46280-a01c-11ea-8cdc-5f1f1124dbb0.png)

Hope that clears things up. If you're still stuck let me know and we'll figure it out.

**Comment by axjurado** [comment]
thanks chris, i think i  got that part right. 

what i don't know is what to change in the firmware to make it work. Tried the serial_port2 3 but didn't work, nor turning on the bluetooth. Any ideas?

BTW Rumba+ is really solid, and want to update it to the rumba32, any idea when will be in stock ?

Thanks for your prompt response and help!

**Comment by chrissbarr** [comment]
Hmm, I'm not overly familiar with the WiFi Backpack module, so I'm working through this from reading the wiring info here:

http://panucattdevices.freshdesk.com/support/solutions/articles/1000277389-wiring-guide-wifi-backpacks

I'd check to make sure that RX and TX are connected around the right way (Backpack TX to RUMBA+ RX, and vice-versa). Note the cross-over.

Your Marlin configuration sounds correct - `#define SERIAL_PORT_2 3` should enable the correct port.

I see in the backpack docs [here](http://panucattdevices.freshdesk.com/support/solutions/articles/1000277681-connecting-to-wifi) that there's a mention of configuring the serial baudrate - you'll want to check that this setting matches your Marlin configuration.

I d not believe that it's necessary to enable Bluetooth in Marlin - as long as the correct port is enabled, that should be the only thing necessary.

Glad to hear you're happy with the RUMBA+ design! I've got a batch of an updated version of RUMBA32 in the works at the moment, if all goes well they should be available in 5-6 weeks.

Let me know if you're still stuck and we'll dig further.

**Comment by axjurado** [comment]
Thanks Chris, again.

The Panucatt tech support replied to use #define SERIAL_PORT2 -1, but i thought that 3 was the right number. Does that make sense? I'm not well versed in Marlin to be honest.

Great to hear that the rumba32 will be available soon. Thanks again!

Augusto

**Comment by chrissbarr** [comment]
No worries Augusto!

I'm fairly sure that `-1` does not map to a serial port on RUMBA+ and would just be the same as having PORT2 disabled.

There are 4 serial interfaces on the microcontroller in RUMBA+. Here's my understanding of where they go:

UART0  - UART to the 16u2 USB Interface (so this is the USB serial port)
UART1  - maps to pins in EXP1 header
UART2  - unused, maps to pins used for stepper drivers
UART3  - maps to pins in EXP3 header

If you were not going to use USB, you could have port 2 disabled (`SERIAL_PORT_2 -1`) and set port 1 to use UART3 (`SERIAL_PORT 0`). Perhaps the Panucatt support were trying to suggest something like this?

**Comment by axjurado** [comment]
Doing SERIAL_PORT_2 3 worked. The -1 wouldn't compile.

My issue with connecting looks like was the baur rate on the wifi backpack.Now it communicates and is working fine.

Thanks for your help! and look forward to the rumba32 to be available!
