### ISSUE TITLE
BT Extension

### ISSUE THREAD

**Issue by evandavey** [Aus3D/RUMBA-Plus#3]
Can a JYU-MCU module be attached similar to http://reprap.org/wiki/RAMPS_1.4#BT_Extension?

**Comment by chrissbarr** [comment]
It should definitely be possible. RUMBA+ has all the same pins that are exposed on RAMPS, and a few extra.

I don't have one of the BT modules to test with, but from the look of things the easiest way would be to use pins on the header EXP3, and wire similar to RAMPS. The 5V and GND pins are there, and then you could use PJ1 / D14 as TxD and PJ0 / D15 as RxD. You'd need the same resistors shown in the RAMPS drawing - I didn't check but I assume those values are correct

I've just added a pinout image to the [main page of the repo](https://github.com/Aus3D/RUMBA-Plus), that should help in finding the pins listed above. Note that the pins above (D14 and D15) correspond to serial port 3 in the Arduino setup, so you'd want to change to that port in Marlin:
```
/**
 * Select which serial port on the board will be used for communication with the host.
 * This allows the connection of wireless adapters (for instance) to non-default port pins.
 * Serial port 0 is always used by the Arduino bootloader regardless of this setting.
 *
 * :[0, 1, 2, 3, 4, 5, 6, 7]
 */
#define SERIAL_PORT 3
```

**Comment by evandavey** [comment]
Ok, thanks.  Will post back if successful.

**Comment by evandavey** [comment]
No success so far.  I have used serial passthrough code to successfully communicate with the module on a stock Arduino Mega (send AT, get OK).  D14 TXD3 is connected to the RXD of the module (with logic translation through a resistor divider), and D15 RXD3 to the TXD of the module.  Module VCC and GND is connected to the Mega 5V/GND.   But I get nothing re-producing this setup on the Rumba+ with module RXD connected to PJ1 on EXP3 and module TXD connected to PJ0 on EXP3. Module VCC / GND is connected to EXP3 5V/GND.  Thoughts?

**Comment by chrissbarr** [comment]
Sorry for the late reply.

It's odd that it isn't working with those two pins - they should be exactly the same pins as on the Arduino Mega. I've been double-checking the pinout and I can't see a problem there, but I might be missing something.

Would it be possible to try a different UART? Maybe D18 (TXD1) and D19 (RXD1), which are on the EXP1 header. I didn't suggest these as they would interfere if you're running an LCD, but maybe it's worth testing with them just to see if it's the same result?
