### ISSUE TITLE
[Question] AUX1 access

### ISSUE THREAD

**Issue by DotBreno** [Aus3D/RUMBA-Plus#9]
First of all, I love how you replaced the PTC fuses with blade ones. I was just about to do something like that myself. Thanks so much.

My question is about the access to RX0 and TX0 pins, the ones that are labeled as AUX1 on RAMPS 1.4. I noticed you wired the pins RXD0 and TXD0 to USB. Are those the same pins I should use? 
I want to do something like [this](https://ae01.alicdn.com/kf/HTB1GWfBSpXXXXcRXVXXq6xXFXXXc.jpg?size=104893&height=623&width=892&hash=ad338f0ff6dfabbbb9f1c581af6187f4)
Where it says "MKS TFT". That's the connector I want to add. I just dont know which ports RX and TX should I use in your project. Can you help me? 

Also, sorry for the bad english and thanks again for the project.

**Comment by chrissbarr** [comment]
Hi @DotBreno,

I have completely missed this question for 2 years now - my sincere apologies on that. I hope that you figured out a working solution to get the MKS TFT running the way you wanted.

For future reference for anyone else that is trying to do something similar, I recommend using the UART3 pins on the EXP3 header. The EXP3 pinout is as follows:

![image](https://user-images.githubusercontent.com/5538631/82976269-c5212180-a01d-11ea-8f55-4923e35281d2.png)

So pins PJ1 (TX3) and PJ0 (RX3) would connect to the MKS TFT serial.
